<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEZPgmVt\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEZPgmVt/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEZPgmVt.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerEZPgmVt\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerEZPgmVt\srcProdProjectContainer(array(
    'container.build_hash' => 'EZPgmVt',
    'container.build_id' => '5f928524',
    'container.build_time' => 1518817491,
));
