<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZdjXf2U\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZdjXf2U/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZdjXf2U.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZdjXf2U\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZdjXf2U\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ZdjXf2U',
    'container.build_id' => '6d549c7f',
    'container.build_time' => 1518814359,
));
